version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - build


jobs:

  build:
    parallelism: 2
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      #split all c files based on the index ID we're running on, pass subset to gcc compile
      - run:
        name: make
        command: make re